# CMake generated Testfile for 
# Source directory: /home/nik/libprotobuf-mutator/src
# Build directory: /home/nik/libprotobuf-mutator/src
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test.protobuf_mutator_test_0]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_0]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=0;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_1]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_1]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=1;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_2]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_2]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=2;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_3]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_3]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=3;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_4]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_4]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=4;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_5]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_5]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=5;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_6]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_6]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=6;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_7]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_7]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=7;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_8]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_8]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=8;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_9]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_9]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=9;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_10]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_10]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=10;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_11]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_11]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=11;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_12]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_12]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=12;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_13]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_13]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=13;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_14]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_14]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=14;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
add_test([=[test.protobuf_mutator_test_15]=] "mutator_test" "--gtest_color=yes" "AUTO")
set_tests_properties([=[test.protobuf_mutator_test_15]=] PROPERTIES  ENVIRONMENT "GTEST_SHARD_INDEX=15;GTEST_TOTAL_SHARDS=16" _BACKTRACE_TRIPLES "/home/nik/libprotobuf-mutator/src/CMakeLists.txt;51;add_test;/home/nik/libprotobuf-mutator/src/CMakeLists.txt;0;")
subdirs("libfuzzer")
